spring:
  application:
    name: Logistics

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://138.2.121.208:3306/DB
    username: su
    password: '!@private1A'

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    context-path: /